from setuptools import find_packages, setup

setup(
    name="piern-data-synthesis",
    version="0.1.0",
    description="PiERN multi-simulator data synthesis pipeline",
    packages=find_packages(),
    python_requires=">=3.11",
    install_requires=[
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "pandas>=1.5.0",
        "h5py>=3.8.0",
        "pyyaml>=6.0",
        "tqdm>=4.65.0",
        "requests>=2.28.0",
        "flopy>=3.7.0",
        "pandapower>=2.13.0",
        "andes>=2.0.0",
        "pypsa>=1.1.0,<1.2.0",
        "linopy>=0.6.0,<0.7.0",
        "highspy>=1.5.0",
        "xarray>=2025.1.0,<2026.0.0",
        "simpeg>=0.25.0,<0.26.0",
        "fastapi>=0.100.0",
        "uvicorn[standard]>=0.23.0",
        "pydantic>=2.0.0",
        "torch>=2.5.0,<2.6.0",
        "transformers>=4.46.0,<4.47.0",
        "tokenizers>=0.20.0,<0.21.0",
        "accelerate>=1.1.0,<1.2.0",
        "safetensors>=0.4.0,<0.5.0",
    ],
    entry_points={
        "console_scripts": [
            "piern-modflow=piern.simulators.modflow.pipeline:main",
            "piern-simpeg=piern.simulators.simpeg.pipeline:main",
            "piern-power=piern.simulators.power_flow.pipeline:main",
            "piern-transient=piern.simulators.transient.pipeline:main",
            "piern-gcam=piern.simulators.gcam.pipeline:main",
        ],
    },
)
